// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"mock_project/ent/booking"
	"mock_project/ent/passenger"
	"mock_project/ent/predicate"
	"mock_project/ent/ticketowner"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PassengerQuery is the builder for querying Passenger entities.
type PassengerQuery struct {
	config
	limit             *int
	offset            *int
	unique            *bool
	order             []OrderFunc
	fields            []string
	predicates        []predicate.Passenger
	withTicket        *TicketOwnerQuery
	withBookings      *BookingQuery
	modifiers         []func(*sql.Selector)
	loadTotal         []func(context.Context, []*Passenger) error
	withNamedBookings map[string]*BookingQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PassengerQuery builder.
func (pq *PassengerQuery) Where(ps ...predicate.Passenger) *PassengerQuery {
	pq.predicates = append(pq.predicates, ps...)
	return pq
}

// Limit adds a limit step to the query.
func (pq *PassengerQuery) Limit(limit int) *PassengerQuery {
	pq.limit = &limit
	return pq
}

// Offset adds an offset step to the query.
func (pq *PassengerQuery) Offset(offset int) *PassengerQuery {
	pq.offset = &offset
	return pq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pq *PassengerQuery) Unique(unique bool) *PassengerQuery {
	pq.unique = &unique
	return pq
}

// Order adds an order step to the query.
func (pq *PassengerQuery) Order(o ...OrderFunc) *PassengerQuery {
	pq.order = append(pq.order, o...)
	return pq
}

// QueryTicket chains the current query on the "ticket" edge.
func (pq *PassengerQuery) QueryTicket() *TicketOwnerQuery {
	query := &TicketOwnerQuery{config: pq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(passenger.Table, passenger.FieldID, selector),
			sqlgraph.To(ticketowner.Table, ticketowner.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, passenger.TicketTable, passenger.TicketColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBookings chains the current query on the "bookings" edge.
func (pq *PassengerQuery) QueryBookings() *BookingQuery {
	query := &BookingQuery{config: pq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(passenger.Table, passenger.FieldID, selector),
			sqlgraph.To(booking.Table, booking.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, passenger.BookingsTable, passenger.BookingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(pq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Passenger entity from the query.
// Returns a *NotFoundError when no Passenger was found.
func (pq *PassengerQuery) First(ctx context.Context) (*Passenger, error) {
	nodes, err := pq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{passenger.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pq *PassengerQuery) FirstX(ctx context.Context) *Passenger {
	node, err := pq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Passenger ID from the query.
// Returns a *NotFoundError when no Passenger ID was found.
func (pq *PassengerQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{passenger.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pq *PassengerQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Passenger entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Passenger entity is found.
// Returns a *NotFoundError when no Passenger entities are found.
func (pq *PassengerQuery) Only(ctx context.Context) (*Passenger, error) {
	nodes, err := pq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{passenger.Label}
	default:
		return nil, &NotSingularError{passenger.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pq *PassengerQuery) OnlyX(ctx context.Context) *Passenger {
	node, err := pq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Passenger ID in the query.
// Returns a *NotSingularError when more than one Passenger ID is found.
// Returns a *NotFoundError when no entities are found.
func (pq *PassengerQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{passenger.Label}
	default:
		err = &NotSingularError{passenger.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pq *PassengerQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Passengers.
func (pq *PassengerQuery) All(ctx context.Context) ([]*Passenger, error) {
	if err := pq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pq *PassengerQuery) AllX(ctx context.Context) []*Passenger {
	nodes, err := pq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Passenger IDs.
func (pq *PassengerQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := pq.Select(passenger.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pq *PassengerQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pq *PassengerQuery) Count(ctx context.Context) (int, error) {
	if err := pq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pq *PassengerQuery) CountX(ctx context.Context) int {
	count, err := pq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pq *PassengerQuery) Exist(ctx context.Context) (bool, error) {
	if err := pq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pq *PassengerQuery) ExistX(ctx context.Context) bool {
	exist, err := pq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PassengerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pq *PassengerQuery) Clone() *PassengerQuery {
	if pq == nil {
		return nil
	}
	return &PassengerQuery{
		config:       pq.config,
		limit:        pq.limit,
		offset:       pq.offset,
		order:        append([]OrderFunc{}, pq.order...),
		predicates:   append([]predicate.Passenger{}, pq.predicates...),
		withTicket:   pq.withTicket.Clone(),
		withBookings: pq.withBookings.Clone(),
		// clone intermediate query.
		sql:    pq.sql.Clone(),
		path:   pq.path,
		unique: pq.unique,
	}
}

// WithTicket tells the query-builder to eager-load the nodes that are connected to
// the "ticket" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PassengerQuery) WithTicket(opts ...func(*TicketOwnerQuery)) *PassengerQuery {
	query := &TicketOwnerQuery{config: pq.config}
	for _, opt := range opts {
		opt(query)
	}
	pq.withTicket = query
	return pq
}

// WithBookings tells the query-builder to eager-load the nodes that are connected to
// the "bookings" edge. The optional arguments are used to configure the query builder of the edge.
func (pq *PassengerQuery) WithBookings(opts ...func(*BookingQuery)) *PassengerQuery {
	query := &BookingQuery{config: pq.config}
	for _, opt := range opts {
		opt(query)
	}
	pq.withBookings = query
	return pq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Passenger.Query().
//		GroupBy(passenger.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pq *PassengerQuery) GroupBy(field string, fields ...string) *PassengerGroupBy {
	grbuild := &PassengerGroupBy{config: pq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pq.sqlQuery(ctx), nil
	}
	grbuild.label = passenger.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Passenger.Query().
//		Select(passenger.FieldName).
//		Scan(ctx, &v)
func (pq *PassengerQuery) Select(fields ...string) *PassengerSelect {
	pq.fields = append(pq.fields, fields...)
	selbuild := &PassengerSelect{PassengerQuery: pq}
	selbuild.label = passenger.Label
	selbuild.flds, selbuild.scan = &pq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a PassengerSelect configured with the given aggregations.
func (pq *PassengerQuery) Aggregate(fns ...AggregateFunc) *PassengerSelect {
	return pq.Select().Aggregate(fns...)
}

func (pq *PassengerQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pq.fields {
		if !passenger.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pq.path != nil {
		prev, err := pq.path(ctx)
		if err != nil {
			return err
		}
		pq.sql = prev
	}
	return nil
}

func (pq *PassengerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Passenger, error) {
	var (
		nodes       = []*Passenger{}
		_spec       = pq.querySpec()
		loadedTypes = [2]bool{
			pq.withTicket != nil,
			pq.withBookings != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Passenger).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Passenger{config: pq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := pq.withTicket; query != nil {
		if err := pq.loadTicket(ctx, query, nodes, nil,
			func(n *Passenger, e *TicketOwner) { n.Edges.Ticket = e }); err != nil {
			return nil, err
		}
	}
	if query := pq.withBookings; query != nil {
		if err := pq.loadBookings(ctx, query, nodes,
			func(n *Passenger) { n.Edges.Bookings = []*Booking{} },
			func(n *Passenger, e *Booking) { n.Edges.Bookings = append(n.Edges.Bookings, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range pq.withNamedBookings {
		if err := pq.loadBookings(ctx, query, nodes,
			func(n *Passenger) { n.appendNamedBookings(name) },
			func(n *Passenger, e *Booking) { n.appendNamedBookings(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range pq.loadTotal {
		if err := pq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pq *PassengerQuery) loadTicket(ctx context.Context, query *TicketOwnerQuery, nodes []*Passenger, init func(*Passenger), assign func(*Passenger, *TicketOwner)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Passenger)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.TicketOwner(func(s *sql.Selector) {
		s.Where(sql.InValues(passenger.TicketColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.passenger_ticket
		if fk == nil {
			return fmt.Errorf(`foreign-key "passenger_ticket" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "passenger_ticket" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (pq *PassengerQuery) loadBookings(ctx context.Context, query *BookingQuery, nodes []*Passenger, init func(*Passenger), assign func(*Passenger, *Booking)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Passenger)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.Booking(func(s *sql.Selector) {
		s.Where(sql.InValues(passenger.BookingsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PassengerID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "passenger_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (pq *PassengerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pq.querySpec()
	if len(pq.modifiers) > 0 {
		_spec.Modifiers = pq.modifiers
	}
	_spec.Node.Columns = pq.fields
	if len(pq.fields) > 0 {
		_spec.Unique = pq.unique != nil && *pq.unique
	}
	return sqlgraph.CountNodes(ctx, pq.driver, _spec)
}

func (pq *PassengerQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := pq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (pq *PassengerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   passenger.Table,
			Columns: passenger.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: passenger.FieldID,
			},
		},
		From:   pq.sql,
		Unique: true,
	}
	if unique := pq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passenger.FieldID)
		for i := range fields {
			if fields[i] != passenger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pq *PassengerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pq.driver.Dialect())
	t1 := builder.Table(passenger.Table)
	columns := pq.fields
	if len(columns) == 0 {
		columns = passenger.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pq.sql != nil {
		selector = pq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pq.unique != nil && *pq.unique {
		selector.Distinct()
	}
	for _, p := range pq.predicates {
		p(selector)
	}
	for _, p := range pq.order {
		p(selector)
	}
	if offset := pq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedBookings tells the query-builder to eager-load the nodes that are connected to the "bookings"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (pq *PassengerQuery) WithNamedBookings(name string, opts ...func(*BookingQuery)) *PassengerQuery {
	query := &BookingQuery{config: pq.config}
	for _, opt := range opts {
		opt(query)
	}
	if pq.withNamedBookings == nil {
		pq.withNamedBookings = make(map[string]*BookingQuery)
	}
	pq.withNamedBookings[name] = query
	return pq
}

// PassengerGroupBy is the group-by builder for Passenger entities.
type PassengerGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pgb *PassengerGroupBy) Aggregate(fns ...AggregateFunc) *PassengerGroupBy {
	pgb.fns = append(pgb.fns, fns...)
	return pgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pgb *PassengerGroupBy) Scan(ctx context.Context, v any) error {
	query, err := pgb.path(ctx)
	if err != nil {
		return err
	}
	pgb.sql = query
	return pgb.sqlScan(ctx, v)
}

func (pgb *PassengerGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range pgb.fields {
		if !passenger.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pgb *PassengerGroupBy) sqlQuery() *sql.Selector {
	selector := pgb.sql.Select()
	aggregation := make([]string, 0, len(pgb.fns))
	for _, fn := range pgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pgb.fields)+len(pgb.fns))
		for _, f := range pgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pgb.fields...)...)
}

// PassengerSelect is the builder for selecting fields of Passenger entities.
type PassengerSelect struct {
	*PassengerQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ps *PassengerSelect) Aggregate(fns ...AggregateFunc) *PassengerSelect {
	ps.fns = append(ps.fns, fns...)
	return ps
}

// Scan applies the selector query and scans the result into the given value.
func (ps *PassengerSelect) Scan(ctx context.Context, v any) error {
	if err := ps.prepareQuery(ctx); err != nil {
		return err
	}
	ps.sql = ps.PassengerQuery.sqlQuery(ctx)
	return ps.sqlScan(ctx, v)
}

func (ps *PassengerSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ps.fns))
	for _, fn := range ps.fns {
		aggregation = append(aggregation, fn(ps.sql))
	}
	switch n := len(*ps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ps.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ps.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ps.sql.Query()
	if err := ps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
